---
nodejs_playbook_version: "0.1.7"
nodejs_install_source: build #One of: build (from source), nodesource_debs (works only on debian-based distros)
nodejs_version: "0.10.36"
nodejs_path: "/usr/local/"
nodejs_tmp_dir: "/tmp/"
nodejs_global_packages:
  - nodemon
  - debug
  - foreman
nodejs_version_tag: "v{{nodejs_version}}"
nodejs_file_tag: "node-{{nodejs_version_tag}}"
nodejs_file_name: "{{nodejs_file_tag}}.tar.gz"
nodejs_base_url: "http://nodejs.org/dist/v{{nodejs_version}}/"
nodejs_tarball_url: "{{nodejs_base_url}}{{nodejs_file_name}}"
nodejs_shasum_file: "{{(nodejs_version | version_compare('1.0.0', '>=')) | ternary('SHASUMS256.txt', 'SHASUMS.txt')}}"
nodejs_shasum_url: "{{nodejs_base_url}}{{nodejs_shasum_file}}"
nodejs_shasum_exec: "{{(nodejs_version | version_compare('1.0.0', '>=')) | ternary('sha256', 'sha1')}}sum"
